# Site settings
title: Robotik
email: robotik@utt.fr
description:
    Robotik website
baseurl:
url: http://robotik.utt.fr  # the base hostname & protocol for your site
github_username:  RobotikUTT
gems: [ jekyll-paginate ]
paginate_path: /blog/page:num/
paginate: 5

# Build settings
exclude:
    - "bower.json"
markdown: redcarpet
sass:
    sass_dir: _sass
    load_paths:
        - _sass
        - bower_components/bourbon/app/assets/stylesheets/
        - bower_components/neat/app/assets/stylesheets/
    compressed: true
